# Generated by Django 3.2.19 on 2023-07-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='platform',
            field=models.CharField(choices=[('playstation', 'PLAYSTATION'), ('xbox', 'XBOX'), ('nintendo', 'NINTENDO')], max_length=20),
        ),
    ]
