# Generated by Django 3.2.19 on 2023-07-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_release_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='platform',
            field=models.CharField(max_length=20),
        ),
    ]
