# Generated by Django 3.2.19 on 2023-09-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_release_release_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='platform',
            field=models.CharField(max_length=80),
        ),
    ]
