# Generated by Django 3.2.19 on 2023-07-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_release_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-release_date']},
        ),
    ]
