# Generated by Django 3.2.19 on 2023-07-11 15:41

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_release_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Release',
        ),
        migrations.AddField(
            model_name='article',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='release_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='article',
            name='release_name',
            field=models.CharField(default='game', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='release_platform',
            field=models.CharField(default='platform', max_length=20),
            preserve_default=False,
        ),
    ]
